# -- コンフィギュレーション設定 --
# 以下の内容ページを参照。
# https://juggernautjp.info/getting-started/configuration/
# ↑ 日本語翻訳チームによるもの（ちょっと公式と違う）
# https://blowfish.page/docs/getting-started/
# ↑ 公式サイト

theme = "blowfish"  
baseURL = "https://hokumedai.github.io/"  # 公開サイトの絶対 URL
defaultContentLanguage = "ja"  # 言語インジケーターのないコンテンツは、デフォルトでこの言語になります。

archetype = "archetype"  # Hugo がアーキタイプ ファイル (コンテンツ テンプレート) を検索するディレクトリ
assetDir = "assets"  # Hugo が Hugo パイプ で使用するアセットファイルを検索するディレクトリ
contentDir = "content"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

summaryLength = 0

buildDrafts = false  # ビルド時にドラフトを含めるかどうか
buildExpired = false
buildFuture = true

enableEmoji = true
enableGitInfo = true  # 各ページの .GitInfo オブジェクトを有効にします。これにより、各ページの Lastmod パラメータが、そのコンテンツファイルの最終 git commit 日時を使用して更新されます。
enableRobotsTXT = true

# googleAnalytics = "G-XXXXXXXXX"

[pagination]
  pagerSize = 10

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
