[[main]]
  name = "活動内容"
  pageRef = "activities"
  weight = 10

[[main]]
  name = "勉強会"
  parent = "活動内容"
  pageRef = "activities/seminar"
  weight = 20

[[main]]
  name = "定期ミーティング"
  parent = "活動内容"
  pageRef = "activities/meeting"
  weight = 20

[[main]]
  name = "もくもく会"
  parent = "活動内容"
  pageRef = "activities/mokumoku"
  weight = 20

[[main]]
  name = "記事"
  pageRef = "articles"
  weight = 30

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/hokumedai/"
  weight = 40

[[footer]]
  name = "プライバシー"
  pageRef = "privacy.md"