name: Deploy Hugo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      article-title: ${{ steps.get-title.outputs.title }}
      article-status: ${{ steps.get-title.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Get latest article title and thumbnail
        id: get-title
        run: |
          # PRでマージされた全コミットから新規追加または更新されたmdファイルを探す
          ARTICLE_INFO=$(
            git diff --name-status --diff-filter=AM ${{ github.event.before }} ${{ github.event.after }} | \
            grep -E '^[AM]\s+content/.*\.md$' | \
            head -1 || \
            echo ""
          )

          if [ ! -z "$ARTICLE_INFO" ]; then
            STATUS=$(echo "$ARTICLE_INFO" | awk '{print $1}')
            LATEST_POST=$(echo "$ARTICLE_INFO" | awk '{print $2}')

            TITLE=$(
              awk '/^---$/{flag++; next}
                flag==1 && /^title:/{
                  gsub(/^title: *["\047]?/, "");
                  gsub(/["\047]? *$/, "");
                  print; exit}' "$LATEST_POST" ||
              basename "$LATEST_POST" .md
            )
            echo "title=$TITLE" >> $GITHUB_OUTPUT
            echo "status=$STATUS" >> $GITHUB_OUTPUT
          else
            echo "title=" >> $GITHUB_OUTPUT
            echo "status=" >> $GITHUB_OUTPUT
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Notify Discord
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          ARTICLE_TITLE: ${{ needs.build.outputs.article-title }}
          ARTICLE_STATUS: ${{ needs.build.outputs.article-status }}
        run: |
          if [ ! -z "$ARTICLE_TITLE" ]; then
            if [ "$ARTICLE_STATUS" = "A" ]; then
              MESSAGE="新しい記事「$ARTICLE_TITLE」を公開しました！\nURLはこちらから↓\n${{ steps.deployment.outputs.page_url }}"
            elif [ "$ARTICLE_STATUS" = "M" ]; then
              MESSAGE="記事「$ARTICLE_TITLE」を更新しました！\nURLはこちらから↓\n${{ steps.deployment.outputs.page_url }}"
            else
              MESSAGE="ホームページを更新しました！\nURLはこちらから↓\n${{ steps.deployment.outputs.page_url }}"
            fi
          else
            MESSAGE="ホームページを更新しました！\nURLはこちらから↓\n${{ steps.deployment.outputs.page_url }}"
          fi

          PAYLOAD=$(cat <<EOF
          {
            "content": "$MESSAGE"
          }
          EOF
          )

          curl -H "Content-Type: application/json" \
               -d "$PAYLOAD" \
               $DISCORD_WEBHOOK
